Update run

diff --git a/rootfs/etc/services.d/10-mount-rclone/run b/rootfs/etc/services.d/10-mount-rclone/run
--- a/rootfs/etc/services.d/10-mount-rclone/run
+++ b/rootfs/etc/services.d/10-mount-rclone/run
@@ -1,7 +1,12 @@
 #!/usr/bin/with-contenv sh
 
-if [ -z "$RCLONE_REMOTE" ]; then
-  echo "Error: RCLONE_REMOTE environment variable was not passed to the container."
+if [ -z "$RCLONE_DRIVE" ]; then
+  echo "Error: RCLONE_DRIVE environment variable was not passed to the container."
+  exit 1
+fi
+
+if [ -z "$RCLONE_CACHE" ]; then
+  echo "Error: RCLONE_CACHE environment variable was not passed to the container."
   exit 1
 fi
 
@@ -10,7 +15,7 @@ if [ ! -f /rclone/.rclone.conf ]; then
   exit 1
 fi
 
-mount_command="rclone mount --config=/rclone/.rclone.conf --allow-other --log-level INFO --log-file /rclone/rclone.log --rc $RCLONE_OPTIONS $RCLONE_REMOTE $RCLONE_REMOTE_MOUNT"
+mount_command="rclone mount --config=/rclone/.rclone.conf --allow-other --log-level INFO --log-file /rclone/rclone.log --rc $RCLONE_OPTIONS $RCLONE_CACHE $RCLONE_REMOTE_MOUNT"
 
 echo "Executing mount rclone => $mount_command"
 exec s6-setuidgid abc $mount_command
